### ISSUE TITLE
Save in DeltaChat folder

### ISSUE THREAD

**Issue by mariosabatino** [niendo1/ImapNotes3#10]
Hello, I tried to save notes into the DeltaChat folder to have it also available into the DC app. I inserted a direct link to the IMAP folder but nothing happened.

So, I'll try to reproduce what i did:

1. In edit account of ImapNotes3 I've manually set the IMAP folder. In my case the folder is as follows:
 imap://username%40posteo.net@posteo.de/DeltaChat
2. saved configuration, no error messages
3. Created a note, saved it and synched
4. No note visible into Thunderbird, don't know where ImapNotes3 really saved the note
5.Another try.  In edit account of ImapNotes3 I've manually set the IMAP folder link as follows:
 imap://username%40posteo.net@posteo.de/DeltaChat/Notes 
with no success.

Whould be nice to find a way to intergrate ImapNotes3 and DeltaChat, to have something similar to "Note to myself" into the app.

Ciao

Mario

**Comment by niendo1** [comment]
please try only DeltaChat as Manual imap folder..
For the notes folder for posteo it is just: Notes.
and it is case sensitive...
Error Message will come in the next Release..

**Comment by mariosabatino** [comment]
Thanks for your quick replay.

I changed email provider (@tilde.team) and tried to put only DeltaChat as Manual imap folder.  The app crashes when synchronizing.  I'll try with another email provider in the future.

I also tried to put DeltaChat as note folder in Posteo but I can see only DC messages, not notes.

Whould be nice to have more integration between ImapNotes3 and DC.

Ciao

Mario

**Comment by niendo1** [comment]
Sometimes the app crashes, it need some rework, but I have not enough time..
Does it crash every time?
You have the version from fdroid? if yes, in some days V1.0.16 should show of there..then try again...

For Posteo: if you use DeltaChat, that you see all the messages in this folder.
But you should be able to create new notes.

For posteo notes, you need the folder Notes.
Booth is not possible..or with a second account. But every account can only work on one folder.
