### ISSUE TITLE
Crash when refreshing the list

### ISSUE THREAD

**Issue by opk12** [niendo1/ImapNotes3#13]
When I click the first menu entry from the hamburger menu, to update the list, the app crashes. I set `Drafts` as notes directory and have 4 messages written in other clients.

```
FATAL EXCEPTION: SyncAdapterThread-1
Process: de.niendo.ImapNotes3, PID: 27053
java.lang.NullPointerException: Attempt to read from null array
	at de.niendo.ImapNotes3.Sync.SyncUtils.SaveNoteAndUpdateDatabase(SyncUtils.java:542)
	at de.niendo.ImapNotes3.Sync.SyncUtils.GetNotes(SyncUtils.java:231)
	at de.niendo.ImapNotes3.Sync.SyncAdapter.onPerformSync(SyncAdapter.java:130)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```

Version 1.0-16 from F-droid, on Android 7.1. This is a self-hosted Dovecot instance.

**Comment by woheller69** [comment]
this can happen if 

    rawvalue = notesMessage.getHeader("Subject")

fails. Then rawvalue is still null and 

           if (rawvalue[0].length() >= 2) {

crashes.

     -> if (rawvalue!=null && rawvalue[0].length()>=2) ...

Is all that try...catch stuff needed or can it be done in a cleaner way?

**Comment by opk12** [comment]
This refactors [SyncUtils.java](https://github.com/niendo1/ImapNotes3/blob/master/ImapNotes3/src/main/java/de/niendo/ImapNotes3/Sync/SyncUtils.java) and tries not to change behavior. Not sure if this is close to your coding style though. Licensed under the same license as ImapNotes3. `||` is short-circuit, so it won't evaluate `.substring()` if `.length() < 2`. 

By the way, each source file needs a proper license header according to [the FSF requirements list](https://www.gnu.org/licenses/gpl-howto.html) (should I open a separate ticket for that?)

```java
        // or =?utf-8?Q?l=C3=A4 =C3=B6 =C3=AB?=  -> Base64
        try {
            title = notesMessage.getSubject();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            rawvalue = notesMessage.getHeader("Subject");

            boolean apply_workaround = false
            if (rawvalue != null) {
                apply_workaround = rawvalue[0].length() < 2 || !(rawvalue[0].substring(0, 2).equals("=?"))
            }

            if (apply_workaround) {
                title = new String(title.getBytes(StandardCharsets.ISO_8859_1));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // Get INTERNALDATE
```

**Comment by niendo1** [comment]
Actually the code can be removed at all (maybe). I don't know exactly why here the subject is read.
Normally the first line of the message itself is the title and becomes the subject.
This case is only for messages, which are not created by Imapnotes..or where Imapnotes creates an empty title..and subject.

**Comment by woheller69** [comment]
maybe necessary for compatibility with Apple's way to manage notes?

If s.o. also has an iPhone?

**Comment by niendo1** [comment]
I have no I phone, but I think I read somewhere it is not compatible...

**Comment by niendo1** [comment]
As I have posteo..I removed everything related to rawvalue = notesMessage.getHeader("Subject");
And it seems still working...

**Comment by woheller69** [comment]
In general I think it would be cleaner to have a separate field for the subject and not take it from the first line of the text and synchronize that with the email subject on the server...

**Comment by woheller69** [comment]
Can you edit the subject when logged into posteo web mailer?

**Comment by woheller69** [comment]
In your fix rawvalue in line 492 can still be null and crash...
 -> if (rawvalue!=null && rawvalue[0].length.....

**Comment by niendo1** [comment]
Lines 475 to 508 is completly commented Out.

**Comment by niendo1** [comment]
Ppste

> Can you edit the subject when logged into posteo web mailer?

Posteo also uses the First Line as Title and subject..and If First Line is empty there ist no Title.

**Comment by niendo1** [comment]
> 
no its not working with posteo. if I create the note in the web note editor the encoding is wrong..

**Comment by opk12** [comment]
Just a heads up to report that it's not crashing anymore now. 👍
