### ISSUE TITLE
`title` can be `null` in SyncUtils.java (potential crash)

### ISSUE THREAD

**Issue by opk12** [niendo1/ImapNotes3#16]
In [`SyncUtils.SaveNoteAndUpdateDatabase()`](https://github.com/niendo1/ImapNotes3/blob/master/ImapNotes3/src/main/java/de/niendo/ImapNotes3/Sync/SyncUtils.java#L457),
- `title` is initialized to `null`
- If `title = notesMessage.getSubject()` fails, then `title` stays `null`
- [OneNote()](https://github.com/niendo1/ImapNotes3/blob/master/ImapNotes3/src/main/java/de/niendo/ImapNotes3/Data/OneNote.java) is passed `null`.

So the issue is twofold:
- `SyncUtils.SaveNoteAndUpdateDatabase()` should handle `notesMessage.getSubject()` failure.
  - Maybe initialize `title = ""` or `"(No title)"`?
- [OneNote constructor arguments](https://github.com/niendo1/ImapNotes3/blob/master/ImapNotes3/src/main/java/de/niendo/ImapNotes3/Data/OneNote.java) should have `@NonNull`

**Comment by niendo1** [comment]
thanks for the hint
I fixed this...
