### ISSUE TITLE
`MessageInternaldate` can be `null` in SyncUtils.java (potential crash)

### ISSUE THREAD

**Issue by opk12** [niendo1/ImapNotes3#17]
In [`SyncUtils.SaveNoteAndUpdateDatabase()`](https://github.com/niendo1/ImapNotes3/blob/master/ImapNotes3/src/main/java/de/niendo/ImapNotes3/Sync/SyncUtils.java#L457), if `notesMessage.getReceivedDate()` fails, `Utilities.internalDateFormat.format()` is given `null` which will raise an NPE (`java.text.SimpleDateFormat(...).format(null)`).

Siilar issue for `title` was opened as #16.

**Comment by niendo1** [comment]
fixed this too...
