### ISSUE TITLE
Custom port is reset when opening settings

### ISSUE THREAD

**Issue by opk12** [niendo1/ImapNotes3#21]
- Make an account with SSL enabled and a custom port number.
- Make some notes.
- Open the account settings.
- The port number was reset to 993.

**Comment by niendo1** [comment]
hopefully fixed in V1.1, but I cant really test...

**Comment by opk12** [comment]
Thank you! I will test 👍

**Comment by opk12** [comment]
Just a heads up to confirm that this is fixed. Thank you again
