### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [niendo1/ImapNotes3#23]
https://monitor.f-droid.org/builds/log/de.niendo.ImapNotes3/10100#site-footer

I don't know why the repo is not cloned but it's weird to clone a repo out of the current repo. Could you please use a git submodule instead?

**Comment by niendo1** [comment]
I did but I need a
`prebuild: ./gradlew submodulesUpdate`
in the yml file

**Comment by niendo1** [comment]
Am 08.03.2024 13:12 schrieb Licaon_Kter: 

> @niendo1 [1] can you retag https://github.com/niendo1/ImapNotes3/tree/v1.3-5 [2] as v1.3-05 to be consistent with the old tags? 
> 
> ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6350865756#L458 [3] 
> 
> —
> Reply to this email directly, view it on GitHub [4], or unsubscribe [5].
> You are receiving this because you were mentioned.Message ID: ***@***.***>
 

Links:
------
[1] https://github.com/niendo1
[2] https://github.com/niendo1/ImapNotes3/tree/v1.3-5
[3] https://gitlab.com/fdroid/fdroiddata/-/jobs/6350865756#L458
[4]
https://github.com/niendo1/ImapNotes3/issues/23#issuecomment-1985587917
[5]

**Comment by niendo1** [comment]
@Licaon_Kter: Yes. I did it already. Thanks!

Am 08.03.2024 13:12 schrieb Licaon_Kter: 

> @niendo1 [1] can you retag https://github.com/niendo1/ImapNotes3/tree/v1.3-5 [2] as v1.3-05 to be consistent with the old tags? 
> 
> ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6350865756#L458 [3] 
> 
> --
> Reply to this email directly, view it on GitHub [4], or unsubscribe [5].
> You are receiving this because you were mentioned.Message ID: ***@***.***>
 

Links:
------
[1] https://github.com/niendo1
[2] https://github.com/niendo1/ImapNotes3/tree/v1.3-5
[3] https://gitlab.com/fdroid/fdroiddata/-/jobs/6350865756#L458
[4]
https://github.com/niendo1/ImapNotes3/issues/23#issuecomment-1985587917
[5]

**Comment by licaon-kter** [comment]
Thanks

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6648298154#L821 

will diff soon

**Comment by licaon-kter** [comment]
diff: [ima10306.log](https://github.com/niendo1/ImapNotes3/files/15024177/ima10306.log)

looks like https://f-droid.org/docs/Reproducible_Builds/#mismatched-toolchains but it can't be it since @niendo1 you use Java 17 too, right?

**Comment by niendo1** [comment]
Hi,

In the project I have:
compileOptions {
  sourceCompatibility JavaVersion.VERSION_17
  targetCompatibility JavaVersion.VERSION_17
}

But gradle uses jdk 21.0.1

Whats better?
Use Version 21 at all or 17 also for gradle..

For 21 the yml file have to be changed...



Am 18.04.2024 13:35 schrieb Licaon_Kter:

> diff: ima10306.log [1]
> 
> looks like 
> https://f-droid.org/docs/Reproducible_Builds/#mismatched-toolchains [2] 
> but it can't be it since @niendo1 [3] you use Java 17 too, right?
> 
> --
> Reply to this email directly, view it on GitHub [4], or unsubscribe 
> [5].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/niendo1/ImapNotes3/files/15024177/ima10306.log
[2] https://f-droid.org/docs/Reproducible_Builds/#mismatched-toolchains
[3] https://github.com/niendo1
[4] 
https://github.com/niendo1/ImapNotes3/issues/23#issuecomment-2063654749
[5]

**Comment by licaon-kter** [comment]
Debian Bookworm has 17 by default, can you use it? Does the app need anything from 21?

**Comment by niendo1** [comment]
can you try again?

I compiled again with jbr-17 and replaced the apk in the release. 

Thanks!

Am 18.04.2024 13:50 schrieb Licaon_Kter: 

> Debian Bookworm has 17 by default, can you use it? Does the app need anything from 21? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you were mentioned.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/niendo1/ImapNotes3/issues/23#issuecomment-2063679120
[2]

**Comment by licaon-kter** [comment]
Checks out, thanks

**Comment by licaon-kter** [comment]
I guess you want v1.4-02 to be skipped? https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8685787687

**Comment by niendo1** [comment]
Hi, 

the actual release 1.4-02 is marked as pre-release, it is not supposed
to be a public release on f-droid.
It is just for testing.
It failed, because its compiled with debug enabled.

Is there a way to set a pre-release without triggering the fdroid build
cycle?

Am 19.12.2024 12:10 schrieb Licaon_Kter: 

> I guess you want v1.4-02 to be skipped? https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8685787687 [1] 
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you were mentioned.Message ID: ***@***.***>
 

Links:
------
[1]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8685787687
[2]
https://github.com/niendo1/ImapNotes3/issues/23#issuecomment-2553441271
[3]

**Comment by linsui** [comment]
You can add a `-alpha` suffix to the tag and add a regex to UpdateCheckMode to exclude it.

**Comment by niendo1** [comment]
ok..
Changed

AutoUpdateMode: Version ^v?[0-9][0-9.]*-[0-9.]*$ 
Hope it works,
Thank you!

Am 19.12.2024 15:48 schrieb linsui: 

> You can add a -alpha suffix to the tag and add a regex to UpdateCheckMode to exclude it. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you were mentioned.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/niendo1/ImapNotes3/issues/23#issuecomment-2554406035
[2]

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/17737

**Comment by licaon-kter** [comment]
@niendo1 you've tagged 1.4-02, we've autoupdate to it

You've changed your mind and deleted the tag

We tried to build... so we failed

You made a new tag 1.4.-02-1, but the version code was not bumped, hence no new version towpick up

We tried to add it manually, its APK is not built from the tagged commit tree... but from the second to last commit...

:(

**Comment by niendo1** [comment]
Hi, 

yep, there was a nasty bug, so I deleted the apk.

Now I checked out tag 4b9c966eece69ee3122c386257e69c9ee68f3483
(V1.4-2-1)
and created a new apk and put in the v1.4-2-1 release.
Or is it better to release a new version with a bumped version code?

Thanks!

Peter

Am 04.01.2025 09:55 schrieb Licaon_Kter: 

> @niendo1 [1] you've tagged 1.4-02, we've autoupdate to it 
> 
> You've changed your mind and deleted the tag 
> 
> We tried to build... so we failed 
> 
> You made a new tag 1.4.-02-1, but the version code was not bumped, hence no new version to pick up 
> 
> We tried to add it manually, its APK is not built from the tagged commit tree... but from the second to last commit... 
> 
> :( 
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you were mentioned.Message ID: ***@***.***>
 

Links:
------
[1] https://github.com/niendo1
[2]
https://github.com/niendo1/ImapNotes3/issues/23#issuecomment-2570832368
[3]

**Comment by licaon-kter** [comment]
The APK in releases/ should always be built from a clean clone checkedout at the commit of the tag .

If you did that now, it's enough.
