### ISSUE TITLE
[Feature Request] Insert date and time

### ISSUE THREAD

**Issue by Aufschlauer** [niendo1/ImapNotes3#24]
I've been used "Note Everything" in the past and I like the Feature "Insert date" and "Insert time".
I'd love to have the same feature in ImapNotes3.

To visualize my feature request and I've appended a ScreenShot of "Note Everything".

![Screenshot_20230308-101525](https://user-images.githubusercontent.com/7963032/223673704-5e7328d6-f27d-4cf8-8acd-9175af833fe1.png)

**Comment by niendo1** [comment]
I will add an icon which will insert date & time..

**Comment by niendo1** [comment]
fixed in v1.2
