### ISSUE TITLE
Italian localisation

### ISSUE THREAD

**Issue by albarron** [niendo1/ImapNotes3#28]
Hi,

as part of my lesson, students of the Specialised Translation Masters at Università di Bologna have created the Italian localisation of ImapNotes3.

If you are willing to integrate it, I could create a pull request with it.

thanks

**Comment by niendo1** [comment]
Yes, of course..please create a pull request..

**Comment by niendo1** [comment]
You can also just send the XML file..

**Comment by albarron** [comment]
Hi, We are polishing a bit. I expect to do the pull request next week
