### ISSUE TITLE
add new or edit existing note from the mail server

### ISSUE THREAD

**Issue by midros** [niendo1/ImapNotes3#35]
Is there a way to add a new note or edit an existing one from the notes folder of the server?

I tried to create a new message on the server, save it in drafts folder and then move it to notes folder, but in the imapnotes app after sync all I see is a blank note.

**Comment by niendo1** [comment]
This should work..for HTML and plain Text Mails. Can you please send the header of the created E-Mail?

**Comment by midros** [comment]
Yes it works. 

My fault.
The msgs in drafts folder were encrypted by default and I missed it. I unchecked this option and everything is fine now.

Sorry and thanks for your time
