### ISSUE TITLE
Not working with web.de

### ISSUE THREAD

**Issue by woheller69** [niendo1/ImapNotes3#4]
My account is accepted.
I create a message and sync it, no error messages.
Add same account to another phone and sync. 
No notes found.

Shouldn't there be an error message if upload to the server fails?

I also tried to set the folder name to Drafts which should be available.

**Comment by niendo1** [comment]
please add an ordner "Notes". Big "N", the rest small. 
After Synchronisation (Abgleich), all the Notes on the mobile are gone, but new ones will be saved.
At least on my account.
I will have a look for the missing message in the next days.

**Comment by woheller69** [comment]
So I have to create the folder in Web.de first.
The app does not create the folder if it does not exist, right?

**Comment by woheller69** [comment]
I created the folder and it works now, thanks!
Would it be possible to let the app create the folder if it does not exist?

**Comment by niendo1** [comment]
in version 1.0.16 the folder will be created
