### ISSUE TITLE
Custom port is reset if switching TLS variant

### ISSUE THREAD

**Issue by opk12** [niendo1/ImapNotes3#43]
This is very minor and I do not really care, but I have set a custom port and `SSL/TLS (accept all certificates)`. When I clicked on the combo box and selected `SSL/TLS` just to try, the port was reset the port to 993.

**Comment by niendo1** [comment]
The port should be reset, otherwise a normal user, has trouble to get the default port, when changing the security mode.
And the sec. mode is only changed one time, when the account is created, or isn't?
