### ISSUE TITLE
Notes getting deleted

### ISSUE THREAD

**Issue by woheller69** [niendo1/ImapNotes3#48]
Again one of my notes got deleted - while sleeping.

Last week (09.08.23) I made a backup of the internal files folder. Note 17 which I created a long time ago and did not modify had a size of 537 bytes.
Now file 17 is still there but with 0 bytes.

**Comment by woheller69** [comment]
![Note-ok](https://github.com/niendo1/ImapNotes3/assets/68678880/725b4092-2045-463a-8771-eecbcba3a460)
![Note-deleted](https://github.com/niendo1/ImapNotes3/assets/68678880/bbe3f2ab-48f4-4b2b-a46e-fe6954e2a820)
![Note-deleted2](https://github.com/niendo1/ImapNotes3/assets/68678880/391e71cf-d38a-4aa7-9ffa-83443bf103d2)

**Comment by woheller69** [comment]
I restored the note from my backup to the internal files folder, opened the empty note in the app and saved it again. Now it is restored. 
Maybe another check during sync is needed. Maybe if an error occurs during sync the file size is 0 bytes. In this case that should not overwrite the existing note.

**Comment by woheller69** [comment]
The bug report created by the app does not contain stuff from today morning.

The note was not modified and should not have changed on the server. I am syncing with 2 other devices but these weren't touched either.

**Comment by woheller69** [comment]
And even if a note was modified the file size should not be 0 bytes as is still contains some header data, right?

**Comment by woheller69** [comment]
the other devices are on manual sync only. Will switch off auto sync also on this device

**Comment by niendo1** [comment]
> And even if a note was modified the file size should not be 0 bytes as is still contains some header data, right?
the file is a normal email with X-Headers and all the stuff, so it should not be empty. That is correct.

**Comment by niendo1** [comment]
I checked the files on my phone (3 accounts), and none of the files is empty...
And most of the files are from May. ( I made a fresh install)

I will check, what happened when an empty file is synced..at least this should not work at all
So, on server side the note should not touched..if so, its an error.
But it will take some time...

**Comment by woheller69** [comment]
if a file has 0 bytes you will see it as empty message at the top of your notes.

I already had that 1-2 times before and thought I had created an empty message.

Next time I will remove the account and add it again. It then should sync from server.

Why doesn't a simple sync restore the file? Does the sync routine not compare the file sizes on the phone  and on the server?

**Comment by niendo1** [comment]
so..files will be silently reloaded from server, if size is < 1.
BUT, it I have still no idea, why some files a getting shrinked to zero..

**Comment by niendo1** [comment]
> Does the sync routine not compare the file sizes on the phone and on the server?
No, It just uses the UID..every time a message is created or changes the mail server gives a new UID.
If (I don`t know how), a remote message has the same uid as the local one, but its complete different, it will not be downloaded
If someone uses a program to change messages remote, without changing the uid, something will go wrong for sure
