### ISSUE TITLE
Question regarding sync

### ISSUE THREAD

**Issue by woheller69** [niendo1/ImapNotes3#5]
Does the app sync notes according to the interval in background also or only when the app is in foreground (which would be enough in my view)?

**Comment by niendo1** [comment]
at least it should be. the sync adapter should work, if the app is not in foreground.
But it should be deactivated if sync interval  is zero.
This part of the code I never touched...

**Comment by woheller69** [comment]
Zero is not available...

**Comment by niendo1** [comment]
should be fixed in master...
