### ISSUE TITLE
Quotation marks are not allowed in account name

### ISSUE THREAD

**Issue by codechipped** [niendo1/ImapNotes3#52]
Version v1.3-03
Pixel 7 Pro Android 13 build TQ3A.230901.001

![photostudio_1696974484363.png](https://github.com/niendo1/ImapNotes3/assets/29626515/3bc103cb-4050-41b0-b3bf-88ab51790fe7)

Not sure why it insists that I have quotes in my username. I typed it by hand, tried autofill, nothing.

**Comment by niendo1** [comment]
Hi,
please enter a name for your NotePad. MyNotepad is just the hint.
But the coloring suggests something else, as its brighter then the normal text...
And the error message should also give a hint..
I will fix this...
