### ISSUE TITLE
Notes get stuck "please wait until save is complete"

### ISSUE THREAD

**Issue by sborrill** [niendo1/ImapNotes3#88]
I edited a note in an area with poor mobile signal so it failed to sync back immediately. Since then, I am unable to open the note. A small pop-up appears briefly at the bottom of the screen saying "please wait until save is complete". Attempting a refresh makes no difference. All other notes are fine.

Version V1.3-07 (problem remained after an update)

**Comment by niendo1** [comment]
Hi, sborrill

Please check with your regularly email program the folder Notes in your IMAP.
You can also Create a Backup. This is a normal zip file, where you can have a look for this message.

To resolve this error, just go to app settings and delete all data and cache from this app. And do a manual sync. This will rebuild the local database with the data from the server.

I will have a look at this issue and how to avoid this as soon as I have soma time...

**Comment by 77nnit** [comment]
I had a similar issue. I was keeping a list opened, editing it during the day. At some point I got the "please wait until save is complete" warning. I went to my webmail provider (posteo.de) and also there the notes were not accessible (I got an error there as well). I honestly don't know if it was my provider or the app. I created a new note on ImapNotes and it worked locally, but everything unblocked when I created a new note on my provider's webapp.
