### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by woheller69** [niendo1/ImapNotes3#9]
Sometimes I have sync problems. I am using the app on 2 devices with 1 account.
I just changed some notes on one device and synced with the server.
Then I synced it with the other device -> fine 
Identical notes on both devices.

Then I killed the app on the second device and opened it again.
The second phone is now back to the status before syncing my latest changes.
Syncing does not work. If I click on the modified message it tells "Abgleich nötig"
but it does not sync.

To fix it I have to go back to the first device, save the note again and sync.

Then the second device syncs again.

So when the app gets killed it seems some stuff is not yet saved

Edit: In this case I made a change in the first line (title?) of the message

**Comment by woheller69** [comment]
maybe an issue of concurrent access to the database.

Read/write methods in the database should be synchronized

Something like

public **synchronized** void  InsertANoteInDb

**Comment by woheller69** [comment]
and database open / close should be done inside these synchronized methods

**Comment by niendo1** [comment]
thank you for taking your time to find and explain issues and bugs!
There are some more bugs related to sync...I know..

Some times it helps "force close" the app via android. and/or delete data and/or cache.
And sync manually.
Account data will not be deleted.

I will have a look at it...as soon I have a rainy sunday afternoon..

**Comment by niendo1** [comment]
so, thanks to your good example, I could do it very fast...
but some of the issues are still remain...

**Comment by woheller69** [comment]
probably all the methods that read/write folders and files containing the messages should also be synchronized

**Comment by niendo1** [comment]
By the way..I was a little bit confused.in your SQLLiteHelper there are in some functions (like public synchronized void updateCityToWatch(CityToWatch cityToWatch))  no  database.close();
It should be everywhere? or is this is that intentional?

**Comment by niendo1** [comment]
And I found the problem, but I'm not sure yet how to solve:
1) if you edit a message it get the temporary number (like -1)
    --> in this moment it it accessible with this number 
2) if you save it..it get transferred to the server. On the server it gets a new UID. and is reloaded to the mobile
   --> the message with ID -1 is delete on the phone 
3) and then the message  gets the its real ID
   --> it is now accessible with the new ID
         but the List needs a refresh, to get the new ID

if you kill the app, the message is transferred to to server and so on..this seems to work in background
but nobody receives the broadcast, that the sync is done.
So there is no refresh list.
If you resume the app, it still tries to access the message with -1..
A manual refresh helps.

But I'm not sure how I trigger the refresh...
refreshList() onResume will crash...

**Comment by woheller69** [comment]
good point, these close statements should be added. But this is obviously not a big problem as long the methods are synchronized

**Comment by woheller69** [comment]
what about syncFinishedReceiver? Can that update the database?

**Comment by woheller69** [comment]
and what does the logcat say why refreshList()  crashes in onResume()?

**Comment by niendo1** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.niendo.ImapNotes3, PID: 3445
    java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131230902, class android.widget.ListView) with Adapter(class de.niendo.ImapNotes3.NotesListAdapter)]
        at android.widget.ListView.layoutChildren(ListView.java:1717)

I guess some **synchronized** are missing...

**Comment by woheller69** [comment]
As the logcat says a notifyDataSetChanged() is missing.

There is one in syncFinishedReceiver

if (isChanged) {
                    storedNotes.GetStoredNotes(noteList, accountName, getSortOrder());
                    listToView.notifyDataSetChanged();
                }


maybe try without the if clause

**Comment by woheller69** [comment]
or try moving that stuff (or part of it) from onCreate to onResume


        this.noteList = new ArrayList<>();
        //((de.niendo.ImapNotes3) this.getApplicationContext()).SetNotesList(this.noteList);
        this.listToView = new NotesListAdapter(
                this,
                this.noteList,
                new String[]{OneNote.TITLE, OneNote.DATE},
                new int[]{R.id.noteTitle, R.id.noteLastChange},
                OneNote.BGCOLOR);

        ListView listview = findViewById(R.id.notesList);
        listview.setAdapter(this.listToView);

        listview.setTextFilterEnabled(true);

        Imaper imapFolder = new Imaper();
        ((ImapNotes3) this.getApplicationContext()).SetImaper(imapFolder);

        storedNotes = NotesDb.getInstance(getApplicationContext());

        // When item is clicked, we go to NoteDetailActivity
        listview.setOnItemClickListener((parent, widget, selectedNote, rowId) -> {
            Log.d(TAG, "onItemClick");
            Intent toDetail = new Intent(widget.getContext(), NoteDetailActivity.class);
            toDetail.putExtra(NoteDetailActivity.selectedNote, (OneNote) parent.getItemAtPosition(selectedNote));
            toDetail.putExtra(NoteDetailActivity.useSticky, ListActivity.ImapNotesAccount.usesticky);
            toDetail.putExtra(NoteDetailActivity.ActivityType, NoteDetailActivity.ActivityTypeEdit);
            startActivityForResult(toDetail, SEE_DETAIL);
            Log.d(TAG, "onItemClick, back from detail.");

**Comment by woheller69** [comment]
and maybe this has to be considered for UpdateThread

https://stackoverflow.com/questions/8665676/how-to-use-notifydatasetchanged-in-thread

**Comment by niendo1** [comment]
from https://stackoverflow.com/questions/44149921/broadcast-receiver-not-working-when-app-is-closed

I faced this issue recently. The BroadcastReceiver was working fine even if the app was removed from the background in the 
emulator and Samsung phones. But it failed to start my app in Chinese manufactured phones like Realme, Mi etc. While struggling to find a way to fix this I found that in the app details page there is battery optimisation settings where the Auto-launch feature was disabled. After I enabled it the app was working fine and BroadcastReceiver was able to start the app. I was unable ti find a way to enable this setting programmatically but I found this [question](https://stackoverflow.com/questions/44383983/how-to-programmatically-enable-auto-start-and-floating-window-permissions) which helped me direct the user to that setting page.

It seems now working...

**Comment by woheller69** [comment]
I set sync interval to 0 but it still auto syncs maybe every 20min.
Even after reboot...

**Comment by niendo1** [comment]
fun fact: on my oneplus it is not working at all :-(
But I have new fix...

**Comment by niendo1** [comment]
is the problem still there, or can I close this issue?

**Comment by woheller69** [comment]
I haven't had any problems for a while
